# Welcome to Jekyll!
title: 个人简历
url:
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: zh-CN                    # html lang
open: true                  # open or close your site
date_format: "%Y-%m-%d"     # date format
theme_color: "#1DA1F2"      # your favorite theme color
allow_search_engines: true  # allow search engines indexing your resume
analytics:
  google:                   # your google analytics
  cloudflare:               # your cloudflare analytics
